import type { Metadata } from "next";
import { Inter, Poppins, Quintessential } from "next/font/google";
import "../globals.css";
import Navbar from "./components/navbar";

const inter = Inter({ subsets: ["latin"] });

const poppins = Poppins({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

const quintessential = Quintessential({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-quintessential"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${poppins.variable} ${quintessential.variable}`}>
        <div className="h-screen bg-white">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
